### ISSUE TITLE
Options for output space?

### ISSUE THREAD

**Issue by lizgregory1** [HALFpipe/HALFpipe#124]
I haven't found an option in halfpipe to change the output space of the preprocessed image. Halfpipe seems to use the default fMRIprep template space (MNI152NLin2009cAsym) as the spatial standardization reference and there doesn't seem to be an option to modify the output space. 

It would be nice to have the option to select a different output space. For example, with fMRIprep, a command line flag can be used to choose the output space (--output-spaces MNI152NLin6Asym, for instance). Perhaps an option to select from a list of common output spaces (I believe there are 3 embedded in fMRIprep) could be included in one of the steps in specifying first-level features or preprocessing? 

If there is already an option embedded in halfpipe that I have missed, please let me know :) I could not find anything referencing this in the documentation.

**Comment by HippocampusGirl** [comment]
Dear @lizgregory1, 

This is a design choice that we made to enforce harmonization across users. Our goal is that all statistical maps derived using HALFpipe should be easily comparable. Being able to switch templates may compromise this goal. 

Could you explain a bit more why this is necessary for your project?

**Comment by HippocampusGirl** [comment]
In case your asking because you need to use a specific atlas or region mask that is not available in MNI152NLin2009cAsym space, `HALFpipe` will automatically warp these to the correct space. For more details on how this is done, please see our pre-print at <https://doi.org/gddf>.

I will close this issue for now, but please feel free to re-open. I am very happy to discuss this :-)
